# Managed with ansible
<VirtualHost *:80>
  ServerName autoconfig.{{autoconfig}}
  DocumentRoot /var/www/autoconfig
  RewriteEngine On
  RewriteCond %{REQUEST_URI} !.well-known/acme-challenge
  RewriteRule ^(.*)$ https://autoconfig.{{autoconfig}}$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
  ServerName autoconfig.{{autoconfig}}
  DocumentRoot /var/www/autoconfig
  SSLEngine on
  SSLCertificateFile /etc/letsencrypt/live/autoconfig.{{autoconfig}}/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/autoconfig.{{autoconfig}}/privkey.pem

  <Directory /var/www/autoconfig>
    Order allow,deny
    allow from all
  </Directory>
</VirtualHost>

