---
- name: get nanolist binary
  get_url:
    url: https://github.com/arnaudmorin/nanolist/releases/download/v0.0.3/nanolist
    dest: /usr/local/bin/

- name: set execution mode on binary
  file:
    path: /usr/local/bin/nanolist
    mode: '0755'

- name: create nanolist folders
  file:
    state: directory
    path: "{{item}}"
    owner: vmail
    group: vmail
  loop:
    - /etc/nanolist/
    - /var/log/nanolist/
    - /var/vmail/nanolist/

- name: configure nanolist
  template:
    src: ./config/nanolist.ini
    dest: "/etc/nanolist/{{item.name}}.ini"
  loop: "{{nanolist.domains}}"

- name: make sure log file exists
  file:
    state: touch
    path: "/var/log/nanolist/{{item.name}}.log"
    mode: 0644
    owner: vmail
    group: vmail
  loop: "{{nanolist.domains}}"

- name: make sure db has correct rights
  file:
    state: touch
    path: "/var/vmail/nanolist/{{item.name}}.db"
    mode: 0644
    owner: vmail
    group: vmail
  loop: "{{nanolist.domains}}"

# Now to add a new ml
# nanolist --config /etc/nanolist/domain.ini create --name="RMCS" --description="Liste du Radio Model Club Senonais" rmcs@example.fr
#
# Also, add the new ml in virtual_users table
#
# Finally, add users to the ml
# nanolist --config /etc/nanolist/domain.ini subscribe arnaud@example.fr rmcs@lists.example.fr
